dist: bionic

language: go
go: 1.13.1

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y upx

install:
  - go mod download
  - go get github.com/google/wire/cmd/wire

script:
  - wire ./src
  - go test ./... -coverpkg=./... -coverprofile=coverage.txt -covermode=atomic -race -tags test
  - CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o build/govolutto.zip && upx build/govolutto.zip
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t maslick/govolutto .

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker push maslick/govolutto