scrape_configs:
- job_name: govolutto
  scrape_interval: 10s
  metrics_path: /v1/metrics
  static_configs:
  - targets:
    - 192.168.8.100:8080
  metric_relabel_configs:
  - source_labels: [__name__]
    target_label: __name__
    replacement: "govolutto_${1}"
